### ISSUE TITLE
Docfx template app restructuring

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx-template#228]
Start using npm packages instead of adding them manually. Let's get together and define the whole docfx-template architecture.

Related items:
- [x] Clean up /styles folder - it should be used only for styles, not having other logic (as it currently has) (Fix provided in #263)
- [x] Configure a build, which outputs only the files necessary for the docfx template to work properly (Fix provided in  #263)
- [x] Remove the custom logic from the docfx.js file
- [x] Update to ES6 or Typescript
- [x] Use npm packages instead of minified copy code
- [ ] Reload only the topic container part of the page #229
- [ ] Right side affix new design implementation:

![image](https://user-images.githubusercontent.com/11193764/104588898-bdc48c00-5671-11eb-935b-0f66f3854c90.png)

**Comment by zdrawku** [comment]
Related with https://github.com/IgniteUI/igniteui-docfx-template/issues/262
